import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  ja: {
    chat: 'チャット',
    admin: '管理画面',
    logout: 'ログアウト',
    startNewChat: '新規チャット',
    typeQuestionTitle: '質問を入力してください',
    typeQuestionSub: '社内ドキュメントに基づいて回答します',
    inputPlaceholder: '質問を入力してください...',
    botListTitle: 'チャットボット一覧',
    botListSub: 'この一覧はサンプルです。「Edit」から個別管理画面に遷移します。',
    edit: 'Edit',
    back: '戻る',
    botSettingsMenu: 'ボット設定メニュー',
    docManage: 'ドキュメント管理',
    docManageSub: 'SharePointの指定フォルダからファイルを一括取得し、チャット用のRAGデータとして取り込みます。各ドキュメントごとに、回答への参照元リンクの表示有無（参照）や、ファイルごとの取り込み方法（選択肢）を個別に設定できます。',
    sysPrompt: 'システムプロンプト',
    botAdmins: 'Bot管理者設定',
    botAdminSub: 'このボットの管理者を設定します。',
    botSettingsTab: 'チャットボット設定',
    spBotLink: 'SharePoint リンク',
    spBotLinkSub: '連携済みのSharePointフォルダパスです（変更不可）',
    creator: '作成者',
    createdAt: '作成日時',
    updatedAt: '最終更新日時',
    deleteBot: 'ボットを削除',
    deleteBotSub: 'この操作は取り消すことができません。RAGデータもすべて削除されます。',
    chatScreenUrl: 'チャット画面URL：',
    copied: 'コピーしました！',
    cannotDeleteSelf: '自分自身は削除できません',
    deleteLabel: '削除',
    noAdmins: '管理者がいません',
    generalSettings: '一般設定',
    save: '保存',
    botDescription: 'ボットの説明',
    botDescriptionNote: '※チャット画面に表示されます',
    botDescriptionExample: '例: このボットは社内規定やマニュアルについて回答します。',
    botPurpose: '利用用途',
    botPurposeExample: '例: 社内ヘルプデスクなど',
    defaultLanguage: 'デフォルト表示言語',
    japanese: '日本語',
    sampleQuestions: 'サンプル質問',
    sampleQuestionsNote: '※チャット画面に3つまで表示されます',
    sampleQuestion1Placeholder: '質問例1を入力...',
    sampleQuestion2Placeholder: '質問例2を入力...',
    sampleQuestion3Placeholder: '質問例3を入力...',
    systemPrompt: 'システムプロンプト',
    systemPromptNote: '※ボットの前提となる人格や振る舞い',
    systemPromptDefault: 'あなたは社内のヘルプデスクアシスタントです。社内規定に基づき、丁寧かつ簡潔に回答してください。',
    contactInfo: '問い合わせ先',
    contactInfoNote: '※チャット画面の下部に表示されます',
    contactMessageExample: '問題が解決しない場合は、以下のフォームよりお問い合わせください。',
    contactLinkPlaceholder: 'フォームURL（任意）を入力...',
    confirmDeleteBot: '削除の確認',
    cancel: 'キャンセル',
    sampleNav: 'これはサンプル遷移です。',
    docListTitle: 'ドキュメント一覧と処理',
    docListSub: 'ドキュメントの処理方法を設定します。\n• 参照（チェックボックス）：回答にドキュメントの参照リンクを表示するかを設定できます。\n• 処理方法（ドロップダウン）：ドキュメントをどのようにRAGに取り込むかを選択します。',
    batchImportTitle: 'SharePointフォルダからの一括データ取込',
    batchImportSub: 'SharePoint の指定フォルダ内のファイルを一括でRAG化する想定のサンプル表示です。',
    spFiles: 'SharePointフォルダ内のファイル',
    update: '更新',
    processPdfBookmarks: 'しおり（見出し）ごとにテキスト処理',
    processPdfImages: 'ページ単位で画像化して処理',
    processExcelTable: 'テーブルとして処理',
    processExcelRow: '行単位で処理',
    processExcelImage: 'シートを画像化して処理',
    processCsvTable: 'テーブルとして処理',
    processCsvRow: '行単位で処理',
    reference: '参照',
    imported: '取込済',
    statusSynced: '取り込み済みファイル群',
    statusNew: '新規 (未取込)',
    statusUpdated: '変更あり',
    statusDeleted: 'SPから削除済',
    descUpdated: 'SharePoint上で更新されたファイルです。同期すると最新のデータがRAGの回答に反映されます。',
    descNew: 'SharePointに新しく追加されたファイルです。処理方法を選んで同期すると、RAGが参照するようになります。',
    descDeleted: 'SharePointから既に削除されています。同期を実行するとRAGのデータからも完全に削除されます。',
    descSynced: '処理方式を変更するとドキュメントが再処理されます。',
    syncSummary: '同期サマリー',
    pendingChanges: '保留中の変更',
    upToDate: 'すべて最新です',
    syncAction: '変更を同期する',
    startImport: '一括取込開始',
    syncButton: 'SharePointと同期 (一括処理)',
    syncDeletedNotice: '※同期時にRAGから削除',
    sysPromptSub: 'チャットボットごとに保存されます。',
    save: '保存',
    sysPromptPlaceholder: 'ボットの振る舞いや回答の形式などを指示するシステムプロンプトを入力してください...',
    botAdminSub: 'メールアドレスを1つずつ追加できます。',
    sampleScreenAlert: 'サンプル画面です',
    sampleScreenAlertSub: 'この画面は見た目確認用で、機能は連携していません。',
    emailPlaceholder: 'メールアドレスを入力',
    add: '＋ 追加',
    recommendedSettings: '推奨される処理設定について',
    pdfCase: '■ PDFの場合',
    excelCase: '■ Excel/PowerPoint/Wordの場合',
    csvCase: '■ CSVの場合',
    bookmarkProcessDesc: '：しおりごとに処理します。テキストが中心のPDFを処理する場合に選択してください。',
    imageProcessDesc: '：PDFを画像に変換して処理します。画面のスクリーンショット等の画像が多く貼られている場合に選択してください。',
    tableProcessDesc: '：テーブルを検出して処理します。通常の表はこちらを選択してください。',
    rowProcessDesc: '：一行ずつデータ化します。問い合わせQA集などはこちらを選択してください。',
    sheetImageProcessDesc: '：シートを画像に変換して処理します。画面のスクリーンショットなどの画像が多い場合はこちら。',
    botDescription: 'ボットの説明',
    botDescriptionNote: '※チャット画面に表示されます',
    botPurpose: '利用用途',
    systemPromptLabel: 'システムプロンプト',
    systemPromptNote: '※ボットの前提となる人格や振る舞いを設定します',
    defaultLanguage: 'デフォルト表示言語',
    sampleQuestions: 'サンプル質問',
    sampleQuestionsNote: '※チャット画面の初期表示に3つまで表示されます',
    sampleQuestion1Label: 'サンプル質問1:',
    sampleQuestion2Label: 'サンプル質問2:',
    sampleQuestion3Label: 'サンプル質問3:',
    contactInfo: '問い合わせ先',
    contactInfoNote: '※チャット画面の下部に表示されます',
    contactMessageLabel: 'メッセージ:',
    contactLinkLabel: 'フォームURL:',
    csvTemplateWarning: '※CSVで一斉追加するには、先にテンプレートをダウンロードしてください。',
    accessUsersExplanation: '何も設定されていない場合は、URLを知っている全員がアクセス可能です。',
    basicSettings: '基本設定',
    unentered: '未入力',
    notSet: '未設定',
    others: '他',
    count: '件',
    allUsers: 'ALL',
    selectDocs: 'ドキュメントごとに設定を選択してください',
    chatContactMessage: '問題が解決しない場合は、以下のフォームよりお問い合わせください。',
    chatContactLink: 'お問い合わせ先',
    referenceDisplayMethod: 'の表示方法',
    openRelevantSection: '該当箇所を開く',
    openFullDocument: 'フルドキュメントで開く',
    headerTitle: '社内規定・マニュアル検索',
    headerSubtitle: 'powered by AI bot',
    adminHeaderTitle: 'Sharepoint bot management',
    adminHeaderSubtitle: 'powered by AI bot',
    noEmails: '登録されたメールアドレスはありません。',
    bot1Name: '社内規程Bot',
    bot1Desc: '就業規則・旅費規程などの社内規程を参照するBot（編集可）',
    bot2Name: '製品FAQ Bot',
    bot2Desc: '製品に関するFAQドキュメントを参照するBot（サンプル・編集不可）',
    bot3Name: 'ITヘルプデスクBot',
    bot3Desc: '社内IT手順書を参照するBot（サンプル・編集不可）',
    sampleResponse: `概要（社内ルールについての質問である前提）：
• 目的: 社内ルールは、標準手順・役割分担・承認経路を定義し、業務の一貫性とコンプライアンスを担保します。[社内規程（2025）]
• 適用対象: 原則として社員・契約社員などの関係者が対象で、例外条件はルール内に定義されます。[社内規程（2025）]
• 確認ポイント: 適用範囲、施行日/版、必要な承認、禁止事項、問い合わせ/エスカレーション先。[社内規程（2025）]
• 一般的な流れ: 申請/根拠準備 → 上長承認 → 関係部門確認（必要時） → 実施 → 記録保管。[旅費規程（2024）]
• 迷った場合: より厳格な解釈を優先し、ルール所管部門または上長に確認してください。

注: この画面はバックエンドと接続していないUI-onlyサンプルです。SharePointフォルダからドキュメントを読み出す想定です。`,
    createNewBot: '新規作成',
    stepTitleSpUrl: 'SharePoint設定',
    stepTitleDocs: 'ドキュメント設定',
    stepTitlePrompt: 'プロンプト設定',
    stepTitleOther: 'その他設定',
    stepTitleAdmin: '管理者設定',
    stepTitleConfirm: '設定確認',
    nextStep: '次へ',
    createAction: '作成',
    confirmCreateMessage: 'チャットボットの作成を開始しますがよろしいですか？\\n※SharePointからの初期データの取り込みには数分かかる場合があります。',
    spUrlSettingLabel: 'データを連携するSharePointのフォルダURLを入力してください。設定後は変更できません。',
    spUrlPlaceholder: 'https://...',
    botNameLabel: 'チャットボット名',
    botNamePlaceholder: '例: 経費精算ヘルプBot',
    confirmSettingLabel: '以下の内容でチャットボットを作成します。',
    confirmNoteEditable: '※設定内容は、ドキュメントの処理方式以外は作成後も変更可能です。',
    waitScanning: '自動スキャン待機中...',
    scanComplete: 'スキャン完了',
    sampleDocCount: '件のドキュメントを検出しました。',
    accessUsers: 'アクセス許可ユーザー',
    accessUsersSub: 'このチャットボットを閲覧・利用できるユーザーを設定します。直接入力またはCSVで一括追加が可能です。',
    csvDownload: 'CSVテンプレート',
    csvUpload: 'CSVアップロード',
    editLabel: '変更',
    stepTitleAccess: 'アクセス権限',
    confirmDeleteBotMessage: 'このチャットボットを削除します。実行してもよろしいですか？',
  },
  en: {
    chat: 'Chat',
    admin: 'Admin',
    logout: 'Logout',
    startNewChat: 'New Chat',
    typeQuestionTitle: 'Enter your question',
    typeQuestionSub: 'Answers will be based on internal documents',
    inputPlaceholder: 'Type your question...',
    botListTitle: 'Chatbot List',
    botListSub: 'This is a sample list. Click "Edit" to configure each bot.',
    edit: 'Edit',
    back: 'Back',
    botSettingsMenu: 'Bot Settings Menu',
    docManage: 'Documents',
    docManageSub: 'Batch extract files from the specified SharePoint folder as RAG data for chat. Set references on/off and configure processing methods per document individually.',
    sysPrompt: 'System Prompt',
    botAdmins: 'Bot Admins',
    botAdminSub: 'Configure bot administrators.',
    botSettingsTab: 'Chatbot Settings',
    spBotLink: 'SharePoint Link',
    spBotLinkSub: 'Linked SharePoint folder path (cannot be changed)',
    creator: 'Creator',
    createdAt: 'Created At',
    updatedAt: 'Last Updated',
    deleteBot: 'Delete Bot',
    deleteBotSub: 'This action cannot be undone. All RAG data will also be deleted.',
    chatScreenUrl: 'Chat Screen URL:',
    copied: 'Copied!',
    cannotDeleteSelf: 'Cannot delete yourself',
    deleteLabel: 'Delete',
    noAdmins: 'No administrators',
    generalSettings: 'General Settings',
    save: 'Save',
    botDescription: 'Bot Description',
    botDescriptionNote: '* Displayed on chat screen',
    botDescriptionExample: 'Example: This bot answers questions about internal policies and manuals.',
    botPurpose: 'Purpose',
    botPurposeExample: 'Example: Internal Help Desk',
    defaultLanguage: 'Default Display Language',
    japanese: 'Japanese',
    sampleQuestions: 'Sample Questions',
    sampleQuestionsNote: '* Up to 3 displayed on chat screen',
    sampleQuestion1Placeholder: 'Enter sample question 1...',
    sampleQuestion2Placeholder: 'Enter sample question 2...',
    sampleQuestion3Placeholder: 'Enter sample question 3...',
    systemPrompt: 'System Prompt',
    systemPromptNote: '* Bot persona and behavior',
    systemPromptDefault: 'You are an internal help desk assistant. Please answer politely and concisely based on internal policies.',
    contactInfo: 'Contact Information',
    contactInfoNote: '* Displayed at bottom of chat screen',
    contactMessageExample: 'If the issue persists, please contact us via the form below.',
    contactLinkPlaceholder: 'Enter Forms URL (optional)...',
    confirmDeleteBot: 'Confirm Deletion',
    cancel: 'Cancel',
    sampleNav: 'This is a sample navigation.',
    docListTitle: 'Document List and Processing',
    docListSub: 'Configure document processing methods.\n• Reference (Checkbox): Set whether to show this document\'s reference link in answers.\n• Processing Method (Dropdown): Choose how to import the document into RAG.',
    batchImportTitle: 'Batch Data Import from SharePoint',
    batchImportSub: 'A sample showing expected batch RAG import from a specified SharePoint folder.',
    spFiles: 'Files in SharePoint Folder',
    update: 'Update',
    processPdfBookmarks: 'Process as text by bookmarks (headings)',
    processPdfImages: 'Process page-by-page as images',
    processExcelTable: 'Process as table',
    processExcelRow: 'Process row-by-row',
    processExcelImage: 'Process as image',
    processCsvTable: 'Process as table',
    processCsvRow: 'Process row-by-row',
    reference: 'Ref',
    imported: 'Imported',
    statusSynced: 'Imported file groups',
    statusNew: 'New',
    statusUpdated: 'Modified',
    statusDeleted: 'Missing in SP',
    descUpdated: 'Files updated on SharePoint. Synchronize to reflect the latest data in RAG answers.',
    descNew: 'Newly added files to SharePoint. Select a processing method and sync to make them active.',
    descDeleted: 'Files already deleted from SharePoint. Synchronizing will remove them completely from RAG.',
    descSynced: 'Changing the processing method will reprocess the document.',
    syncSummary: 'Sync Summary',
    pendingChanges: 'Pending Changes',
    upToDate: 'All up to date',
    syncAction: 'Sync Changes',
    startImport: 'Start Import',
    syncButton: 'Sync with SharePoint',
    syncDeletedNotice: '*Will be removed from RAG',
    sysPromptSub: 'Saved per chat bot.',
    save: 'Save',
    sysPromptPlaceholder: 'Enter system prompts to dictate bot behavior or response formats...',
    botAdminSub: 'You can add email addresses one by one.',
    sampleScreenAlert: 'Sample Screen',
    sampleScreenAlertSub: 'This screen is for visual confirmation only; functionality is not connected.',
    emailPlaceholder: 'Enter email address',
    add: '+ Add',
    recommendedSettings: 'Recommended Processing Settings',
    pdfCase: '■ PDF',
    excelCase: '■ Excel/PowerPoint/Word',
    csvCase: '■ CSV',
    bookmarkProcessDesc: ': Process by bookmarks. Select for text-heavy PDFs.',
    imageProcessDesc: ': Convert PDF to images and process. Select for PDFs with many screenshots.',
    tableProcessDesc: ': Detect and process as tables. Select for standard tables.',
    rowProcessDesc: ': Process row by row. Select for Q&A datasets.',
    sheetImageProcessDesc: ': Convert sheets to images and process. Select for files with many screenshots.',
    botDescription: 'Bot Description',
    botDescriptionNote: '* Displayed on chat screen',
    botPurpose: 'Purpose',
    systemPromptLabel: 'System Prompt',
    systemPromptNote: '* Set the bot persona and behavior',
    defaultLanguage: 'Default Display Language',
    sampleQuestions: 'Sample Questions',
    sampleQuestionsNote: '* Up to 3 displayed on chat screen',
    sampleQuestion1Label: 'Sample question 1:',
    sampleQuestion2Label: 'Sample question 2:',
    sampleQuestion3Label: 'Sample question 3:',
    contactInfo: 'Contact Information',
    contactInfoNote: '* Displayed at bottom of chat screen',
    contactMessageLabel: 'Message:',
    contactLinkLabel: 'Forms link:',
    csvTemplateWarning: '* Download template first for CSV bulk upload.',
    accessUsersExplanation: 'If nothing is set, anyone who has Komatsu Azure AD account and knows the URL can access.',
    basicSettings: 'Basic Settings',
    unentered: 'Not entered',
    notSet: 'Not set',
    others: 'others',
    count: 'items',
    allUsers: 'ALL',
    selectDocs: 'Select settings for each document',
    chatContactMessage: 'If the issue persists, please contact us via the form below.',
    chatContactLink: 'Contact Us',
    referenceDisplayMethod: ' - Display options',
    openRelevantSection: 'Open relevant section',
    openFullDocument: 'Open full document',
    headerTitle: 'Internal Policy & Manual Search',
    headerSubtitle: 'powered by AI bot',
    adminHeaderTitle: 'Sharepoint bot management',
    adminHeaderSubtitle: 'powered by AI bot',
    noEmails: 'No registered email addresses.',
    bot1Name: 'Internal Rules Bot',
    bot1Desc: 'References internal policies like employment and travel rules (Editable)',
    bot2Name: 'Product FAQ Bot',
    bot2Desc: 'References FAQ documents for products (Sample/Non-editable)',
    bot3Name: 'IT Helpdesk Bot',
    bot3Desc: 'References internal IT procedure manuals (Sample/Non-editable)',
    sampleResponse: `Overview (Assuming the question is about internal rules):
• Purpose: Internal rules define standard procedures, roles, and approval routing to ensure business consistency and compliance. [Internal Rules (2025)]
• Scope: Targets primarily stakeholders like employees and contractors, with exception conditions defined within the rule. [Internal Rules (2025)]
• Checkpoints: Scope of application, effective date/version, required approvals, prohibited items, contacts/escalation paths. [Internal Rules (2025)]
• General Flow: Application/Prep → Manager Approval → Dept Confirmation (if needed) → Execution → Record Retention. [Travel Rules (2024)]
• When in doubt: Prioritize stricter interpretations and consult the rule-owning department or your manager.

Note: This is a UI-only sample not connected to a backend. It simulates retrieving documents from a SharePoint folder.`,
    createNewBot: 'Create New',
    stepTitleSpUrl: 'SharePoint URL',
    stepTitleDocs: 'Documents',
    stepTitlePrompt: 'System Prompt',
    stepTitleOther: 'Other Settings',
    stepTitleAdmin: 'Admins',
    stepTitleConfirm: 'Confirmation',
    nextStep: 'Next',
    createAction: 'Create',
    confirmCreateMessage: 'Are you sure you want to start creating the chatbot?\\n* Initial data import from SharePoint may take a few minutes.',
    spUrlSettingLabel: 'Enter the SharePoint folder URL to link data. This cannot be changed later.',
    spUrlPlaceholder: 'https://...',
    botNameLabel: 'Chatbot Name',
    botNamePlaceholder: 'e.g. Expense IT Help Bot',
    confirmSettingLabel: 'The chatbot will be created with the following settings.',
    confirmNoteEditable: '',
    waitScanning: 'Waiting for auto-scan...',
    scanComplete: 'Scan Complete',
    sampleDocCount: 'documents detected.',
    accessUsers: 'Access Users',
    accessUsersSub: 'Set who can view and use this chatbot. You can add users manually or import via CSV.',
    csvDownload: 'CSV Template',
    csvUpload: 'Upload CSV',
    editLabel: 'Edit',
    stepTitleAccess: 'Access Rights',
    confirmDeleteBot: 'Delete Chatbot',
    confirmDeleteBotMessage: 'Are you sure you want to delete this chatbot? This action cannot be undone.',
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ja');
  const t = (key) => translations[lang][key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
